animeapp/animeapp/animeapp/urls.py
import mainapp.views as mainapp

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', mainapp.index),
    path('admin/', admin.site.urls),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('catalog/', mainapp.catalog),
    path('catalog/manga/<int:pk>/', mainapp.manga, name='manga'),
    path('catalog/manga/manga_page<int:pk>/', mainapp.manga_page, name='manga_page'),
    path('catalog/anime/<int:pk>/', mainapp.anime, name='anime'),
    path('catalog/anime/anime_page<int:pk>/', mainapp.anime_page, name='anime_page'),
]

animeapp/animeapp/authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
]

animeapp/animeapp/authapp/models.py
from django.db import models

# Create your models here.

animeapp/animeapp/mainapp/models.py
from django.db import models
import datetime

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

class Manga(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    photo = models.ImageField('Картинка', upload_to='static/img', height_field=None, width_field=None, max_length=100,
                              null=True)
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)
    avtor = models.CharField(max_length=128)
    painter = models.CharField(max_length=128)
    data = models.DateField()
    page = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Манга'
        verbose_name_plural = 'Манга'

class Anime(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    photo = models.ImageField('Картинка', upload_to='static/img', height_field=None, width_field=None, max_length=100,
null=True)
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)
    producer = models.CharField(max_length=128)
    data = models.DateField()
    episodes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Аниме'
        verbose_name_plural = 'Аниме'

animeapp/animeapp/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name',
                  'password1', 'password2', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

animeapp/animeapp/authapp/views.py
import django.contrib.auth as auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, RegisterForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect('/')
    else:
        form = LoginForm()

    context = {
        'page_title': 'авторизация',
        'form': form,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = RegisterForm()

    context = {
        'page_title': 'регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)

animeapp/animeapp/mainapp/views.py
from django.shortcuts import render

from mainapp.models import Category, Manga, Anime


def catalog(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
        'page_title': 'каталог'
    }

    return render(request, 'mainapp/catalog.html', context)


def index(request):
    return render(request, 'mainapp/index.html')


def manga(request, pk):
    Manges = Manga.objects.filter(category_id=pk)
    context = {
        'Manges': Manges,
        'page_title': 'Манга'
    }
    return render(request, 'mainapp/manga.html', context)

def manga_page(request, pk):
    manga = Manga.objects.get(pk=pk)
    context = {
        'manga': manga,
        'page_title': 'Манга'
    }
    return render(request, 'mainapp/manga_page.html', context)


def anime(request, pk):
    Animes = Anime.objects.filter(category_id=pk)
    context = {
        'Animes': Animes,
        'page_title': 'Аниме'
    }
    return render(request, 'mainapp/anime.html', context)

def anime_page(request, pk):
    anime = Anime.objects.get(pk=pk)
    context = {
        'anime': anime,
        'page_title': 'Аниме'
    }
    return render(request, 'mainapp/anime_page.html', context)

animeapp/animeapp/authapp/templates/authapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"аутентификация"|capfirst }}</title>
    {% block css %}
        <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    {% endblock %}
    {% block js %}
        <script src="/static/js/jquery-3.2.1.slim.min.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

animeapp/animeapp/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% block content %}
    <div class="login-form">
        <div class="form-title">Вход в систему</div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"
                   class="btn btn-success form-control"
                   value="войти">
        </form>
        <br>
        <a class="btn btn-info form-control" href="{% url 'auth:register' %}">
            зарегистрироваться
        </a>
    </div>
{% endblock %}

animeapp/animeapp/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% block content %}
    <div class="register-form">
        <div class="form-title">Регистрация</div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"
                   class="btn btn-success form-control"
                   value="зарегистрироваться">
        </form>
    </div>
{% endblock %}

animeapp/animeapp/mainapp/templates/mainapp/anime.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Каталог</h1>

    <div class="navbar navbar-light bg-light">
        <ul class="nav nav-pills flex-column">
            {% for item in Animes %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'anime_page' item.pk %}">
                        {{ item }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>



{% endblock %}

animeapp/animeapp/mainapp/templates/mainapp/anime_page.html
{% block content %}
    <h1>Аниме</h1>
    <p>
        <img class="card-img-top" src="../../../{{ manga.photo }}" alt="Card image">
    </p>
    <p>
       Название: {{ anime.name }}
    </p>
    <p>
        Описание: {{ anime.desc }}
    </p>
    <p>
        Продюсер: {{ anime.producer }}
    </p>
    <p>
        Дата релиза: {{ anime.data }}
    </p>
    <p>
        Эпизоды: {{ anime.episodes }}
    </p>
{% endblock %}

animeapp/animeapp/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
    {% block css %}
         <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="pos-f-t">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="navbar navbar-dark bg-dark">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="/">Главная</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/catalog/">Категория</a>
        </li>
        <li class="nav-item active">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'auth:logout' %}">Выйти</a>
            {% else %}
                <a class="nav-link" href="{% url 'auth:login' %}">Войти</a>
            {% endif %}
        </li>
    </ul>
    <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</div>
</nav>
</div>
{% block content %}
{% endblock %}
</body>
</html>

animeapp/animeapp/mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Каталог</h1>

    <div class="navbar navbar-light bg-light">
        <p>Манга</p>
        <ul class="nav nav-pills flex-column">
            {% for item in categories %}

                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'manga' item.pk %}">
                        {{ item }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="navbar navbar-light bg-light">
        <p>Аниме</p>
        <ul class="nav nav-pills flex-column">
            {% for item in categories %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'anime' item.pk %}">
                        {{ item }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>



{% endblock %}

animeapp/animeapp/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h3>Вот уже много лет японская анимация пользуется огромным успехом по всему миру, включая Россию. Эти ленты любят за яркий сюжет, оригинальную рисовку и неизменный накал эмоций.</h3>
{% endblock %}

animeapp/animeapp/mainapp/templates/mainapp/manga.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>Каталог</h1>

    <div class="navbar navbar-light bg-light">
        <ul class="nav nav-pills flex-column">
            {% for item in Manges %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'manga_page' item.pk %}">
                        {{ item }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>



{% endblock %}

animeapp/animeapp/mainapp/templates/mainapp/manga_page.html
{% block content %}
    <h1>Манга</h1>
    <p>
        <img class="card-img-top" src="../../../{{ manga.photo }}" alt="Card image">
    </p>
    <p>
        {{ manga.name }}
    </p>
    <p>
        Описание: {{ manga.desc }}
    </p>
    <p>
        Автор: {{ manga.avtor }}
    </p>
    <p>
        Художник: {{ manga.painter }}
    </p>
    <p>
        Дата релиза: {{ manga.data }}
    </p>
    <p>
        Главы: {{ manga.page }}
    </p>
{% endblock %}